## Set catppuccin theme
import = [
  "~/.config/alacritty/themes/themes/catppuccin.toml"
]

[font]
size = 16

[font.normal]
family = "JetBrainsMonoNL Nerd Font"

[window]
decorations = "none"
opacity = 0.8

[window.padding]
x = 7
y = 0

## Set tmux as the default shell
[shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-A", "-D", "-s" ,"main"]
