# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = "$env_var$all"

[env_var.ZMX_SESSION]
symbol = " "
format = "[$symbol$env_value]($style) "
description = "zmx session name"
style = "bold green"

[aws]
symbol = "  "

[c]
symbol = " "

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "
disabled = true

[git_branch]
symbol = " "

[golang]
symbol = " "

[hostname]
ssh_symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[os.symbols]
Linux = " "
Macos = " "

[package]
symbol = "󰏗 "

[python]
symbol = " "
pyenv_version_name = false
pyenv_prefix = ""

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = " "

format = """
${env_var.ZMX_SESSION}\
...
"""

