default_session = "main"
recursive_submodules = false

[[search_dirs]]
path = "/Users/milan/Projects"
depth = 3

[[search_dirs]]
path = "/Users/milan/Teaching"
depth = 3

[[search_dirs]]
path = "/Users/milan/R-packages"
depth = 3

[[search_dirs]]
path = "/Users/milan/website/"
depth = 1

[[search_dirs]]
path = "/Users/milan/talks/"
depth = 1

[[search_dirs]]
path = "/Users/milan/obsidian/"
depth = 1
