## Set catppuccin theme
import = ["~/.config/alacritty/themes/themes/catppuccin.toml"]

[font]
size = 14

[font.normal]
family = "JetBrainsMonoNL Nerd Font"

[window]
decorations = "none"
opacity = 0.90

[window.padding]
x = 7
y = 0

## Set tmux as the default shell
[shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-A", "-D", "-s", "main"]
